0,MiniWorldSprites/User Interface/BoxSelector.png,0,0
1,MiniWorldSprites/Ground/Grass.png,16,0
2,MiniWorldSprites/Nature/Rocks.png,0,0
3,MiniWorldSprites/Nature/Trees.png,0,0
4,MiniWorldSprites/Nature/Trees.png,16,0
5,MiniWorldSprites/Nature/Wheatfield.png,0,0
6,MiniWorldSprites/Nature/Wheatfield.png,16,0
7,MiniWorldSprites/Nature/Wheatfield.png,32,0
8,MiniWorldSprites/Nature/Wheatfield.png,48,0
9,MiniWorldSprites/Nature/WinterTrees.png,0,48
10,MiniWorldSprites/Nature/Trees.png,32,0
11,MiniWorldSprites/Buildings/Wood/CaveV2.png,0,0
12,MiniWorldSprites/Buildings/Wood/Houses.png,0,16
13,MiniWorldSprites/Buildings/Wood/Houses.png,0,32
14,MiniWorldSprites/Buildings/Wood/Houses.png,0,48
15,MiniWorldSprites/Buildings/Wood/Resources.png,0,0